name: Add Identifiers
on:
  workflow_dispatch:

jobs:
  identifiers:
    runs-on: macos-12
    steps:
      # Uncomment to manually select latest Xcode if needed
      #- name: Select Latest Xcode
      #  run: "sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer"
      
      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
